### ISSUE TITLE
git pull failed

### ISSUE THREAD

**Issue by MangoTsing** [feross/git-pull-or-clone#10]
`gitPull()` 

I made a mistake with this method.

so i check my code, i use `git pull --depth=1 xxxxx.git` with the following error
```
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
fatal: missing blob object '8aa4e4460bcc8935ea56c7881cebfb619d06a451'
error: remote did not send all necessary objects
```
and i use `git clone --depth=1 xxxxx.git` success

so i must use `git pull xxxxx.git`.

I do not know why it has to be like this.

I guess this is a problem with git, but cant find a way to resolve it

Hope you can help me, thx:)

**Comment by MangoTsing** [comment]
`gitPull()`  Original error

```
(node:95361) UnhandledPromiseRejectionWarning: Error: Non-zero exit code: 1 (git pull) (https://github.com/n/n.git)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@c/c/node_modules/git-pull-or-clone/index.js:55:31)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
(node:95361) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:95361) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
