### ISSUE TITLE
128 error

### ISSUE THREAD

**Issue by zhukunpenglinyutong** [feross/git-pull-or-clone#11]
/Users/zhu/Desktop/node 下载 git demo/index.js:22
  if (err) throw err
           ^

Error: Non-zero exit code: 128 (git pull) (git@github.com:feross/standard.git)
    at ChildProcess.<anonymous> (/Users/zhu/Desktop/node 下载 git demo/node_modules/_git-pull-or-clone@2.0.1@git-pull-or-clone/index.js:55:31)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by feross** [comment]
This error can happen sometimes for various reasons - lost internet connection, git repo is in a bad state. It's not a bug in this package.
